### ISSUE TITLE
Remove additional escaping in /bulk-data/analyze

### ISSUE THREAD

**Issue by mahchiahui** [Senzing/senzing-rest-api-specification#69]
**Describe the bug**
In https://petstore.swagger.io/?url=https://raw.githubusercontent.com/Senzing/senzing-rest-api-specification/master/senzing-rest-api.yaml#/Bulk%20Data/analyzeBulkRecords , you can find that the sample json record has too much escaping done. This would result in an error when a user tries to use the example curl shown in swagger.

To fix it, remove the additional escaping done on the data

**Comment by barrycaceres** [comment]
So I did some research and the escaping is coming from the Swagger editor itself.....

The offending part of the code is this:

```
        content:
          application/x-jsonlines; charset=UTF-8:
            schema:
              type: string
            examples:
              chooseExample:
                $ref: '#/components/examples/chooseExample'
              bulkDataJsonLinesExample:
                $ref: '#/components/examples/bulkDataJsonLinesExample'
          application/x-jsonlines:
            schema:
              type: string
            examples:
              chooseExample:
                $ref: '#/components/examples/chooseExample'
              bulkDataJsonLinesExample:
                $ref: '#/components/examples/bulkDataJsonLinesExample'
```

Other lines also offend.  It is a combination of the `schema` setting with `type` of `string` and media types `application/x-jsonlines` and `application/json` (both of these and their UTF-8 variants have the same problem).

Because it sees that it is a `string` the editor is trying to escape it as such.  However, the only other options for the `type` of the `schema` are as follows: `array`, `boolean`, `integer`, `number`, and `object`

I tried `object` and it does not resolve the problem.  There is no `raw` option.  The only way it seems to work correctly is with the media types `text/plain` and `test/csv` and their UTF-8 variants.

I don't know why the escaping is introduced when non-text media types are used.  I may just omit these examples since they don't display property in the swagger UI -- but I am researching it.

**Comment by barrycaceres** [comment]
Version 2.7.1 resolves this.  I had to modify the `application/json` and `application/x-jsonlines` media type entries to refer to the examples for `text/plain`.  I could change the `application/json` ones to use type `object` with the `additionalProperties: {}` attribute to indicate a generic JSON object, however, the code generator choked on that and produced code that would not compile.

As such, I left all of them producing type `string` for the `schema` but referred the examples to `text/plain` types which actually render correctly in Swagger UI.
